development: &default
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 50
  username: <%= ENV.fetch('PGUSER') %>
  password: <%= ENV.fetch('PGPASSWORD') %>
  host: <%= ENV.fetch('PGHOST') %>
  port: <%= ENV.fetch('PGPORT') %>

test: 
  <<: *default
  database: test

production: 
  <<: *default
  database: production